### ISSUE TITLE
Option to include security classification/handling instructions

### ISSUE THREAD

**Issue by pbbgss** [co-analysis/a11ytables#107]
Hello there!

It would be really useful to be able to add a single line to the top of each sheet containing security classification and handling instructions etc for pre-release versions of publication tables but also for internal MI etc.

**Comment by matt-dray** [comment]
Thanks for this! 

I envisaged originally that rows above a table should be fairly 'fixed'. Examples like yours demonstrate, however, that there's a need for 'arbitrary' information too. I've got this recorded in #74, so for pure admin reasons I'm going to close your issue in favour of that more-generic one.

As an aside, I'm also working to make it easier to add an arbitrary number of rows per section on the cover page as well (see issue #102 and draft pull request #104). This should make it easier to add classification and handling info to the cover, but I know it would be ideal to show this information right next to the tables in question.

**Comment by pbbgss** [comment]
Sounds great - really appreciate your work on this!
