### ISSUE TITLE
Is a print method necessary for a11ytables?

### ISSUE THREAD

**Issue by matt-dray** [co-analysis/a11ytables#23]
Should there be a print method for a11ytable-class objects and what should it be?

To be honest, the tibble view of the object is compact, concise and reinforces that you can interact with the class as though it's a data.frame. However, tibble is not imported, while the output from a data.frame can be a bit excessive (particularly with list-columns). It might be nice for people to see what's in each table itself, rather than just a numierc `dim()`-like description.

For now there's a `print.a11ytables()`, which is just a placeholder really. Maybe it could present on a sheet-by-sheet basis?

```
> lfs_tables |> as_a11ytable() |> print()
# An a11ytable with 5 sheets
 * Tab titles: 
  - cover
  - contents
  - notes
  - 1
  - 2 
 * Sheet types: 
  - cover
  - contents
  - notes
  - tables
  - tables 
 * Sheet titles: 
  - Labour market overview data tables, UK, December 2020 (accessibility example)
  - Table of contents
  - Notes
  - Number and percentage of population aged 16 and over in each labour market activity group, UK, seasonally adjusted
  - Number and percentage of population in each labour market activity group by age band, UK, seasonally adjusted 
 * Table names: 
  - Cover_content
  - Table_of_contents
  - Notes_table
  - Labour_market_summary_for_16_and_over
  - Labour_market_activity_groups_16_and_over 
 * Table sizes: 
  - 17 x 1
  - 2 x 5
  - 11 x 2
  - 6 x 10
  - 6 x 9 
 ```

Example of tibble view of `lfs_tables`:

```
> tibble::as_tibble(lfs_tables)
# A tibble: 5 × 8
  tab_title sheet_type sheet_title                                   source      subtable_num subtable_title table_name          table   
  <chr>     <chr>      <chr>                                         <chr>       <chr>        <chr>          <chr>               <list>  
1 cover     cover      Labour market overview data tables, UK, Dece… NA          NA           NA             Cover_content       <tibble…
2 contents  contents   Table of contents                             NA          NA           NA             Table_of_contents   <tibble…
3 notes     notes      Notes                                         NA          NA           NA             Notes_table         <tibble…
4 1         tables     Number and percentage of population aged 16 … Labour For… NA           NA             Labour_market_summ… <tibble…
5 2         tables     Number and percentage of population in each … Labour For… NA           NA             Labour_market_acti… <tibble…
```

**Comment by TimTaylor** [comment]
I'd consider having this current print output as a the output for a summary method (i.e. `summary.a11ytables()`). For printing I'd prefer to see the data but agree that it looks better as a tibble. If you'd prefer not to do a tibble subclass I'd consider using the **{pillar}** package directly and adding the `tbl` class (i.e the object would have class `c("a11ytables", "tbl", "data.frame")`). This will then let you easily add custom styled headers and the like.

**Comment by matt-dray** [comment]
@TimTaylor Strong agree, so I changed the print method to a summary method. Cheers!
