### ISSUE TITLE
Code of conduct link broken in README.md

### ISSUE THREAD

**Issue by jtrim-ons** [co-analysis/a11ytables#98]
Tiny thing - the link in the "Code of Conduct" section points to a missing .html file rather than CODE-OF-CONDUCT.md

(PS I'm giving a little internal talk this morning about the accessibility checker, but I'm going to spend most of my my time recommending a11ytables and gptables!)

**Comment by matt-dray** [comment]
Great spot. The Code of Conduct md is rendered to html when the documentation wesbite is built, so the README link worked from the website but not from GitHub. I've changed the link so it points to the URL for the website by default. Thanks! I hope the talk went well.
